language: python
python:
    - "2.7"

install: pip install -r requirements.txt
env:
  global:
      secure: <long encrypted string>

script:
    - export SECRET_KEY=$SECRET_KEY
    - python manage.py test
